"use client"
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Provider } from "react-redux";
import ReduxProvider from "@/redux/reduxProvider";
const poppins = Poppins({ 
  weight: ["200","400","500"],
  subsets:['latin']
 });

// export const metadata: Metadata = {
//   title: "Furniro",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>
        <Header/>
        {children}
        <Footer/>
        <ToastContainer/>
        </ReduxProvider>
        </body>
    </html>
  );
}
